language: generic
services:
  - docker

env:
  matrix:
    # - ROS_DISTRO="dashing" ROS_REPO=testing
    # - ROS_DISTRO="dashing" ROS_REPO=main
    # - ROS_DISTRO="eloquent" ROS_REPO=testing
    - ROS_DISTRO="eloquent" ROS_REPO=main
    - ROS_DISTRO="foxy" UPSTREAM_WORKSPACE="additional_repos.repos"

install:
  -  git clone --quiet --depth 1 https://github.com/mikaelarguedas/industrial_ci.git .industrial_ci -b ici_default_nightly_image
script:
  - .industrial_ci/travis.sh
