services:
  - docker

install:
  - git clone --quiet --depth 1 https://github.com/mikaelarguedas/ros2ci.git .ros2ci
  - cp additional_repos.repos .ros2ci/

matrix:
  include:
    - script: .ros2ci/travis.bash dashing
    - script: .ros2ci/travis.bash nightly
