services:
  - docker

install:
  - git clone --quiet --depth 1 https://github.com/mikaelarguedas/ros2ci.git .ros2ci

matrix:
  include:
    - script: .ros2ci/travis.bash dashing
    - script:
      - cp additional_repos.repos .ros2ci/
      - .ros2ci/travis.bash nightly
